//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class distribution
    {
        public int did { get; set; }
        public int oid { get; set; }
        public int eid { get; set; }
        public string status { get; set; }
    
        public virtual user user { get; set; }
        public virtual order order { get; set; }
    }
}
